### PR TITLE
fix(addAlertString): string for when user is caught up on alerts

### PR DESCRIPTION
**Pull request by KemoPaw**
https://satellite-im.atlassian.net/browse/AP-278

### CODE REVIEW

**Review by stavares843 — COMMENTED** [review]
thanks for adding!

we can use " " instead of the \

like this one
https://github.com/Satellite-im/locales/blob/50fc0806a83977b7679c4215ef5edf60d3b5fe5f/en-US.js#L139

**Comment by stavares843** [comment]
thanks for adding! @KemoPaw 🎉 

minor suggestions above

**Comment by KemoPaw** [comment]
> thanks for adding!
> 
> we can use " " instead of the \
> 
> like this one
> 
> https://github.com/Satellite-im/locales/blob/50fc0806a83977b7679c4215ef5edf60d3b5fe5f/en-US.js#L139

@stavares843 Just changed! 😄

**Review by stavares843 — APPROVED** [review]

**Comment by stavares843** [comment]
thanks! 🎉

**Pull request merged**
